feat(template): support global vars as param initializer e.g. templat…
b-laporte/ivy pull request #21
Opened 2020-02-13 08:44 UTC by gpolychronis

…e((state = globalState) => {...})

2020-02-13 10:13 UTC, b-laporte requested changes
Hi - thanks for the PR
As most of the changes touch trax, the code changes should be submitted to the trax repo first.
Regarding the example, I was thinking of updating the pages example instead of creating a new one (each page could be given a global state that they could update through a button for instance)
Thx

2020-02-13 10:13 UTC, b-laporte commented on src/trax/compiler/parser.ts
> +                        //First SK.Identifier is property name. Second one might be a variable as default value.
trax changes should be submitted first on the trax repo (I will share it with you)

2020-02-13 10:13 UTC, b-laporte commented on src/xjs/parser.ts
> -                console.log("TODO: support default value as variable: ", nd.defaultValue);
... and xjs changes should be submitted on the xjs repo :-) (I will also share it with you)

2020-07-06 07:39 UTC, gpolychronis commented
@b-laporte 
Do you need this PR? If not may I decline it?

2020-09-30 14:02 UTC, closed without merging